language: php

php:
  - 7.1
  - 7.2

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - phpenv config-rm xdebug.ini
  - composer install --no-interaction --prefer-dist

script:
  - vendor/bin/phpunit
